### ISSUE TITLE
reports "in quiet hours" even though its not

### ISSUE THREAD

**Issue by caffeinejolt** [kmac/mindfulnotifier#7] opened 2021-03-22 18:32 UTC
App settings specify quiet hours from 9PM to 8AM - at 11:30 AM the app is reporting "In quiet hours".  No notifications are triggered - making the app rather useless.  Any workaround?

**Comment by kmac** [comment] 2021-03-22 18:44
You're right, that is pretty useless.

I think the issue is at line 253 in scheduler.dart, which I found and fixed locally yesterday  https://github.com/kmac/mindfulnotifier/blob/1213829af7a2cca424ae4c3de7766cbaa44927f5/lib/components/scheduler.dart#L253

I'm actually not sure why this is working on my phone... I think it's because my android (Iineage OS) is killing the app overnight, so it is starting out with a new Scheduler instance every morning after quiet hours.

I'm testing out a local change for the next day where I'm refactoring a fair bit of code. I guess what I can do is push a simple fix for this in the interim. I won't be able to do that until tonight, after my work day is done.

In the meantime, as a workaround if you disable/enable in the morning it will work for you for the rest of the day, until the next quiet hours. Sorry for the inconvenience. The behaviour around app getting killed really varies across the android devices, so this one slipped through. I really haven't got any feedback from this app yet - not many people have found it, so I'm afraid you're a beta tester!

**Comment by kmac** [comment] 2021-03-23 00:17
Should be fixed by v1.0.8. If you're still seeing this then please let me know.

**Closed by kmac** 2021-03-23 00:17 UTC
